packageExtensions:
  babel-preset-react-app@*:
    dependencies:
      '@babel/plugin-proposal-private-property-in-object': '*'
  styled-components@*:
    dependencies:
      react-is: '*'
  react-csv@*:
    dependencies:
      'prop-types': '*'
