
# Build environment
FROM node:17-alpine AS Builder
WORKDIR /app
COPY package.json ./
COPY yarn.lock ./
RUN yarn install --immutable --immutable-cache --check-cache
COPY . .
RUN yarn build

# Production environment
FROM nginx:stable-alpine AS Server
COPY --from=Builder ./app/build /usr/share/nginx/html